/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary-dark': '#0D3B66',
        'primary-medium': '#1A5F9E',
        'primary-light': '#3A7BC8',
        'bg-page': '#E8F0FE',
        'bg-card': '#FFFFFF',
        'bg-card-alt': '#F0F4F8',
        'bg-card-blue': '#D0DEF0',
        'bg-info': '#D6E6F5',
        'bg-splash': '#0D3B66',
        'bg-splash-end': '#0A2D4D',
        'status-safe': '#2E8B57',
        'status-warning': '#E8A020',
        'status-error': '#E53935',
        'status-info': '#1A5F9E',
        'accent-gold': '#C9A96E',
        'accent-gold-hover': '#B8944F',
        'text-primary': '#1A1A2E',
        'text-secondary': '#6B7280',
        'text-tertiary': '#9CA3AF',
        'text-link': '#1A5F9E',
        'border-light': '#D1D5DB',
        'border-medium': '#9CA3AF',
        'divider': '#E5E7EB',
        'warning-bg': '#FFF8E7',
        'emergency-warm': '#FFF0F0',
        'emergency-calm': '#F0FFF5',
        'bezel': '#1A1A2E',
        'bg-gallery': '#f8fafc',
        'bg-selected': '#F5F8FD',
      },
      borderRadius: {
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '20px',
        'phone': '40px',
      },
      boxShadow: {
        'card': '0 2px 8px rgba(0, 0, 0, 0.08)',
        'card-hover': '0 4px 16px rgba(0, 0, 0, 0.12)',
        'button': '0 2px 6px rgba(13, 59, 102, 0.2)',
        'phone': '0 20px 60px rgba(0, 0, 0, 0.3)',
        'nav': '0 -2px 10px rgba(0, 0, 0, 0.05)',
      },
      fontFamily: {
        'heading': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'body': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display': ['36px', { lineHeight: '1.1', fontWeight: '800' }],
        'h1': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'h2': ['22px', { lineHeight: '1.3', fontWeight: '700' }],
        'h3': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'body': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-bold': ['16px', { lineHeight: '1.5', fontWeight: '600' }],
        'sm': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
        'xs': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'button': ['18px', { lineHeight: '1', fontWeight: '700' }],
        'button-sm': ['14px', { lineHeight: '1', fontWeight: '600' }],
        'price': ['28px', { lineHeight: '1.1', fontWeight: '700' }],
      },
      spacing: {
        'sp-1': '4px',
        'sp-2': '8px',
        'sp-3': '12px',
        'sp-4': '16px',
        'sp-5': '20px',
        'sp-6': '24px',
        'sp-8': '32px',
        'sp-10': '40px',
        'sp-12': '48px',
      },
    },
  },
  plugins: [],
}
